### ISSUE TITLE
Feedback to your project

### ISSUE THREAD

**Issue by firefighterduck** [TheMC47/random-quote#7]
Hey @TheMC47,

I want to congratulate you on your really cool and well thought out repository.
It has absolutely everything you want a FLOSS project to have.
By simply reading through your repo I learned a lot about features I didn't know Github had :D 
The small problem with the "add a quote" workflow was unfortunate but you solved it immediately and handled the situation professionally.

There is only one change I might suggest and it's more of a personal issue than a real problem that would be solved by it.
You may want to have the "add a quote" guide either directly in the CONTRIBUTING file or at least in another markdown file in the repository itself. This may help keeping your project more independent from the actual platform it is hosted on and allows for more complete local backups in case of server failures (which should be rather unrealistic but how knows).

**Comment by TheMC47** [comment]
Thank you for your kind feedback :smile:  

Regarding the suggestion about the guide, even though you make a fair point, I think I'll keep it as it is. The reason is that I want the contributors to see "ah, this many people added quotes!" just by looking at the emoji. This is the simplest and most accessible way to update, track, and display the number of people who added quotes. 

I'm still willing to have this project as my little playground, I'll probably publish it to hackage and try to generate documentation in haddock. I'll make sure to include the guide there!
